name: vietnam_provinces
description: A Flutter package to manage Vietnam's provinces, districts, and wards.
version: 1.0.2
homepage: https://github.com/14h4i/vietnam_provinces
repository: https://github.com/14h4i/vietnam_provinces
issue_tracker: https://github.com/14h4i/vietnam_provinces/issues

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - lib/assets/provinces.json.gz
